### ISSUE TITLE
No usable version of libssl was found (Debian testing)

### ISSUE THREAD

**Issue by LeoSum8** [MadWalnut/firefly-iii-dkb-csv-fix#3]
Hi there and thanks for this tool!

When I try to run the self-contained version I am getting 

```
No usable version of libssl was found
Aborted
```

any idea?

**Comment by MadWalnut** [comment]
I think this happens because the latest release is from 2021 and it was built targeting an older .NET version. The old .NET versions require OpenSSL 1.0 but current Linux distros (like Debian sid / testing) ship OpenSSL 1.1 and there is no backward compatibility. I assume that if you were to build targeting .NET 6.0 (see 64b0fcc) the error would disappear. Or maybe the old build would even run just fine on something like Debian stable. [ref 1](https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa) / [ref 2](https://github.com/dotnet/core/issues/4749)

As time permits, I'll try to release a new build in the next weeks also incorporating the changes from #2. I need to do some more testing with the new CSV format (used since the banking UI update last year) though.

**Comment by MadWalnut** [comment]
I have released an update, please try [v1.0.6](https://github.com/MadWalnut/firefly-iii-dkb-csv-fix/releases/tag/v1.0.6).

It targets .NET 6.0 which should hopefully fix the issue as explained above. If not please try building yourself (instructions are in README) and targeting the newest .NET available on your distro. I unfortunately do not have a Debian testing instance to try this.

That said, you might want to migrate to using the CSV exports from the new DKB banking anyway. That makes the whole process way easier, see this [pull request](https://github.com/firefly-iii/import-configurations/pull/151) as discussed in #2 and #4.

So I am not sure if it is really worth investigating this issue much further in case v1.0.6 does not fix it. Most people will probably just stop using this program anyway. But do let me know if it is still broken.
