### ISSUE TITLE
Example importconfig.json for firefly data importer

### ISSUE THREAD

**Issue by Richard-Rumpel** [MadWalnut/firefly-iii-dkb-csv-fix#4]
Hey, can somebody provide an example configuration file for the firefly data importer ? Thanks a lot :)

**Comment by MadWalnut** [comment]
I haven't tested this thoroughly, but this seems to work for the new banking format:

```json
{
    "version": 3,
    "source": "ff3-importer-1.4.3",
    "created_at": "2024-02-16T00:32:52+01:00",
    "date": "d.m.y",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [
        "date_book",
        "date_transaction",
        "_ignore",
        "account-name",
        "opposing-name",
        "description",
        "_ignore",
        "account-iban",
        "amount",
        "sepa_ci",
        "sepa_db",
        "internal_reference"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "classic",
    "ignore_duplicate_lines": true,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "flow": "file",
    "content_type": "csv",
    "custom_tag": "",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "grouped_transaction_handling": "",
    "use_entire_opposing_address": false,
    "map_all_data": false,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": false,
    "ignore_duplicate_transactions": true
}
```

It does not seem to pick up the the opposing account correctly on incoming transactions (outgoing works fine). It puts my name in the opposing account field. According to the [documentation](https://docs.firefly-iii.org/references/data-importer/roles/#asset-account) this should switch dynamically, but it doesn't for me... Can anyone confirm? Currently I'm just using a rule as a workaround.

Otherwise it works fine so far. Since the new banking does not support a time ranged export, I just export everything and use the duplicate detection of the importer to filter out lines that were already imported.

Let me know if this config works for you, then I will update official config [here](https://github.com/firefly-iii/import-configurations/tree/main/de/dkb).

**Until I update this script, you need to remove the first 4 lines of the CSV file manually, see #2. Only then the above config will work.**

**Comment by herrwusel** [comment]
Thank you for sharing your configuration file. Did you map the value for `account name`?

I get a `(2)transactions.0.source_id: [a] Could not find a valid source account when searching for ID "0" or name "redacted". (original value: "(not found)")` for every entry of my CSV, although I have rules set up in firefly.

**Comment by MadWalnut** [comment]
No, I did not map the `account name`. Try setting `default_account` in the JSON above to the ID of your DKB account. To find the ID in Firefly go to `Accounts` -> `Asset Accounts` -> `DKB`. Now at the end of the URL there should be a numeric value. For me it is `1` because DKB was the first account I created in Firefly. For you it may be different.

**Comment by herrwusel** [comment]
Thanks, I messed something up. Your config is working, and I don't have the issue with the opposing account field.

**Comment by MadWalnut** [comment]
@herrwusel Perfect. So just to confirm, you removed everything until `"Buchungsdatum"`, so the first 4 lines? 

If yes I will update the [README in the official repo](https://github.com/firefly-iii/import-configurations/tree/main/de/dkb) with this information because that is where people will probably look first and currently the text there is outdated. I will then keep this repo here as the old legacy converter, in case someone needs to import old files.

**Comment by herrwusel** [comment]
Exactly, removing the first four lines, using your config and some use case specific mapping was enough for me.

**Comment by MadWalnut** [comment]
Thank you. I have opened a [pull request in the main repo](https://github.com/firefly-iii/import-configurations/pull/151).

**Comment by albertusQuelle** [comment]
> default_account

Thx, but i dont understand how and what to change. I have the json open and then?

<img width="893" height="677" alt="Image" src="https://github.com/user-attachments/assets/bf3af876-19a8-4a0f-b6b0-73ca59e0a3a7" />

**Comment by MadWalnut** [comment]
@albertusQuelle In line 6 you have to replace `1` with the correct account ID of your DKB account in your Firefly III instance. To check what your id is follow this comment from above:

> To find the ID in Firefly go to `Accounts` -> `Asset Accounts` -> `DKB`. Now at the end of the URL there should be a numeric value. For me it is `1` because DKB was the first account I created in Firefly. For you it may be different.

**Comment by albertusQuelle** [comment]
Hi @MadWalnut  thank you so much for your reply. 

The "1" is my correct number as i created this as the first and only bank account in my fresh firefly installation

**Comment by albertusQuelle** [comment]
update, this error is now gone as i just ignored some more fields. 

But the amount is always 0. 

source file has as delimiter a comma between Euro,Cent

but it seems that while conversion the importer changes this into a point... 

How did you solve this?

**Comment by MadWalnut** [comment]
@albertusQuelle Sorry, I haven't been using the DKB importer for a while now so I can't really say if something has changed. The config I posted above has been working at that time though for what its worth.

**Comment by albertusQuelle** [comment]
Thank you very much. Hmm, the only thing is the amount and i cant and I can't help myself
